### ISSUE TITLE
/bin/sh: 1: /opt/unity/Editor/Data/NetCore/Sdk-*/dotnet: not found

### ISSUE THREAD

**Issue by KirstenMiller3** [shadow7412/unityci#1]
Hey is this project still active?

I get this error when trying to use 

```
/bin/sh: 1: /opt/unity/Editor/Data/NetCore/Sdk-*/dotnet: not found
The command '/bin/sh -c /opt/unity/Editor/Data/NetCore/Sdk-*/dotnet tool install --global dotnet-sonarscanner' returned a non-zero code: 127
```

I think because later versions of unity editor are no longer packaged with dotnet core?

**Comment by shadow7412** [comment]
I would like it to be, but I haven't had a chance to deal with that issue
personally (aside from limiting my unity version)

I'd be very welcoming of a PR.

**Comment by KirstenMiller3** [comment]
I have something working, but I am new to docker and CI so I'm probably doing a lot of stuff badly. Do you think it's still worthwhile doing a PR?

**Comment by shadow7412** [comment]
Absolutely. If you're doing anything excessively terrible, I'll gladly help you fix it up prior to merging.

**Comment by shadow7412** [comment]
Merged #2

**Comment by shadow7412** [comment]
```
Assets/Editor/BuildCommands.cs(18,6): error CS0246: The type or namespace name 'SuppressMessageAttribute' could not be found (are you missing a using directive or an assembly reference?)
Assets/Editor/BuildCommands.cs(18,6): error CS0246: The type or namespace name 'SuppressMessage' could not be found (are you missing a using directive or an assembly reference?)
Assets/Editor/BuildCommands.cs(18,69): error CS0246: The type or namespace name 'Justification' could not be found (are you missing a using directive or an assembly reference?)
```

Do you know which import is required for these?

**Comment by KirstenMiller3** [comment]
https://github.com/sbergen/Responsible/blob/main/ResponsibleUnity/Assets/EditorSetup/ContinuousIntegration.cs#L53-L63 it's maybe missing one of the ones here at the top

**Comment by shadow7412** [comment]
Yep, found them. Thanks.

**Comment by shadow7412** [comment]
Woo, working perfectly now. Thanks for your PR :)

**Comment by KirstenMiller3** [comment]
you're welcome, I've posted a link in the game-ci discord to hopefully help out future people :)
